services:
  backend:
    image: ghcr.io/ja3cob/todo-backend:latest
    ports:
      - ${BACKEND_PORT}:5000
    restart: always
    volumes:
      - ./db:/app/db
    stdin_open: true
  frontend:
    image: ghcr.io/ja3cob/todo-frontend:latest
    ports:
      - ${FRONTEND_PORT}:80
    restart: always
    environment:
      - VITE_SERVER_URL=https://todoapp.mooo.com
    depends_on:
      - backend
