services:
  backend:
    image: todo-backend:latest
    ports:
      - "5040:5000"
    restart: always
    volumes:
      - ./db:/app/db
    stdin_open: true
  frontend:
    image: todo-frontend:latest
    ports:
      - "5041:80"
    restart: always
    environment:
      - VITE_SERVER_URL=https://todoapp.mooo.com
    depends_on:
      - backend