services:
  backend:
    image: ghcr.io/ja3cob/todo-backend:latest
    ports:
      - "5040:5000"
    restart: always
    volumes:
      - ./db:/app/db
    stdin_open: true
  frontend:
    image: ghcr.io/ja3cob/todo-frontend:latest
    ports:
      - "5041:80"
    restart: always
    depends_on:
      - backend
