name: Build and push frontend Docker image

on:
  push:
    branches: [ "main" ]
    paths: [ "todo-frontend/**" ]

jobs:
  build-and-push-frontend-docker-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./todo-frontend
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/todo-frontend:latest
